### PR TITLE
Cr-1014 Upgrade Python version to 3.8.6

### PR DESCRIPTION
**Pull request by MartinHumphrey**
# Motivation and Context
Request to upgrade to latest 3.8 python version. Updates to any available library dependencies.

# What has changed
Updates required to use python 3.8.6. Libraries in pipfile.lock updated, unit tests updated. 

# How to test?
All unit tests run. RH cucumber tests run locally and in dev environment with updated Travis build and Docker file to use python 3.8.6.

### CODE REVIEW

**Review by Paul-Joel — DISMISSED** [review]
LGTM

**Comment by rpcatling** [comment]
We would like to see if we can get a performance run before we merge this ticket, for confidence at load

**Review by rpcatling — CHANGES_REQUESTED** [review]
after the high CPU problems encountered with a performance test that Ella ran today, some investigation and fix is needed before this is ready to merge.

**Comment by MartinHumphrey** [comment]
Performance testing showed increased CPU usage moving to python 3.8.6 using aiohttp as at present.

**Pull request closed without merging**
