### PR TITLE
Cr 1733 missing attributes

### PR DESCRIPTION
**Pull request by Paul-Joel**
# Motivation and Context
Updates all calls for session data (both explicit and implicit) to check the data exists in the session first

# What has changed
Updates calls for session data to check for the data before trying to use it
Change to some page 'return' calls to make the explicit as to the data sent to the page, to ensure all needed values are checked to exist
Addition of a session forget call in start of fulfilment journey to prevent cross session issues

No Cucumber changes required

Note addresses issues in multiple Jira tickets and incidents

# How to test?
Try re-creating the conditions that triggered the various errors. Ensure issue is resolved.

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1733
https://collaborate2.ons.gov.uk/jira/browse/CR-1744
https://collaborate2.ons.gov.uk/jira/browse/CR-1734
https://collaborate2.ons.gov.uk/jira/browse/CR-1755

### CODE REVIEW

**Review by PeterBochel — APPROVED** [review]
Approving with comments:

- It all seems sensible but I need to add the disclaimer that I'm not a Python expert.
- Our continuing problems with sessions/timeouts/etc show that we have gaps in our Cucumber coverage, but probably too late to do much about that now.

**Review by rpcatling — CHANGES_REQUESTED** [review]
I feel that we should have some unit tests for this.

**Comment by rpcatling** [comment]
also please merge with latest HOTFIX code

**Comment by philwhiles** [comment]
Not being done now

**Pull request closed without merging**
